services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${ACHERS_POSTGRES_DB}
      - POSTGRES_USER=${ACHERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ACHERS_POSTGRES_PASSWORD}

  migrate:
    image: ${DOCKER_IMAGE}
    command: sh -c "sleep 10 && python manage.py migrate --noinput"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=achers_myspace.settings.production
    depends_on:
      - db

  web:
    image: ${DOCKER_IMAGE}
    command: sh -c "chown wagtail:wagtail /app/static /app/media && gunicorn achers_myspace.wsgi:application --bind 0.0.0.0:8100"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8100
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=achers_myspace.settings.production
    depends_on:
      migrate:
        condition: service_completed_successfully

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8100:80"
      - "8449:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
